# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-30 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0003_add_submit_date_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('submit_date',), 'permissions': [('can_moderate', 'Can moderate comments')], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AddField(
            model_name='comment',
            name='replay_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='comment',
            name='replay_to',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='root_id',
            field=models.IntegerField(default=0),
        ),
    ]
