# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-03 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0005_auto_20190130_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-submit_date',), 'permissions': [('can_moderate', 'Can moderate comments')], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
