version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker-support/Dockerfile
    tty: true
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - /data/collectstatic:/HuberyBlog/collectstatic
      - /data/media:/HuberyBlog/media
      - /data/log:/HuberyBlog/log
      - /data/database:/HuberyBlog/database
    ports:
      - 80:80
  redis:
    image: redis:latest
    command: redis-server
    ports:
    - "9999:6379"
    volumes:
      - ./data:/data

