# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-30 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='分类名称'),
        ),
    ]
