# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-27 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190130_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='网站名字')),
                ('net_address', models.CharField(max_length=128, verbose_name='网站地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '网站',
                'verbose_name_plural': '网站',
            },
        ),
        migrations.CreateModel(
            name='WebCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='网站名字')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '网站类别',
                'verbose_name_plural': '网站类别',
            },
        ),
        migrations.AddField(
            model_name='web',
            name='web_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.WebCategory', verbose_name='关联网站分类'),
        ),
    ]
