# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-05 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190227_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='留言id')),
                ('name', models.CharField(max_length=32, verbose_name='留言')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '留言',
                'verbose_name': '留言',
            },
        ),
        migrations.AlterField(
            model_name='webcategory',
            name='name',
            field=models.CharField(max_length=32, verbose_name='网站类别'),
        ),
    ]
