# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-06 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190305_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32, verbose_name='访问者ip')),
                ('visit_num', models.IntegerField(default=0, verbose_name='访问次数')),
                ('first_visit_time', models.DateTimeField(auto_now_add=True, verbose_name='第一次访问时间')),
                ('last_visit_time', models.DateTimeField(auto_now=True, verbose_name='最后访问时间')),
            ],
            options={
                'verbose_name': '访问统计',
                'verbose_name_plural': '访问统计',
            },
        ),
    ]
