# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-07 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_visitview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitview',
            name='last_visit_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后访问时间'),
        ),
    ]
