# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-07 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190307_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitview',
            name='last_visit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后访问时间'),
        ),
    ]
