# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-03 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190307_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='博客名称')),
                ('address', models.CharField(max_length=64, verbose_name='博客链接')),
                ('status', models.SmallIntegerField(choices=[(0, '无效'), (1, '有效')], default=1, verbose_name='是否有效')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
            },
        ),
    ]
