# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-03 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_friendsblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitview',
            name='ip_address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='访问地址'),
        ),
    ]
