# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-15 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_web_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, null=True, verbose_name='内容')),
                ('hits', models.CharField(max_length=100, null=True, verbose_name='伤害值')),
            ],
            options={
                'verbose_name': '毒鸡汤',
                'db_table': 'soul',
                'verbose_name_plural': '毒鸡汤',
            },
        ),
    ]
