# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-22 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_soul'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(null=True, verbose_name='block ip')),
                ('status', models.SmallIntegerField(choices=[(0, '无效'), (1, '有效')], verbose_name='是否有效')),
            ],
            options={
                'verbose_name': '黑名单',
                'verbose_name_plural': '黑名单',
                'db_table': 'block_id',
            },
        ),
    ]
