# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-07 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hot',
            options={'ordering': ['sorted']},
        ),
        migrations.AddField(
            model_name='hot',
            name='sorted',
            field=models.SmallIntegerField(default=0, verbose_name='排序'),
        ),
    ]
