# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-07 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot', '0003_auto_20190707_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hot',
            name='hot_name',
            field=models.CharField(max_length=256, null=True, verbose_name='热榜源'),
        ),
    ]
